CREATE DATABASE IF NOT EXISTS `go_db`;
USE `go_db`;

CREATE TABLE IF NOT EXISTS Tasks(
    `Id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `Title` VARCHAR(256) NOT NULL,
    `Description` VARCHAR(256),
    `Created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `Updated_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP
)ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

INSERT INTO Tasks(Title, Description) VALUE('sample', 'hello world');
